name: Create Release

on:
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifactErrorsFailBuild: false
        artifacts: "src/dist/windows/app.exe"
        artifactContentType: "raw"
        bodyFile: "CHANGELOG.md"
        draft: false
        generateReleaseNotes: true
        prerelease: false
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
